"""GCP Storage Constant."""

locations_list = [
    "US",
    "EU",
    "ASIA",
    "ASIA1",
    "EUR4",
    "NAM4",
    "NORTHAMERICA-NORTHEAST1",
    "NORTHAMERICA-NORTHEAST2",
    "US-CENTRAL1",
    "US-EAST1",
    "US-EAST4",
    "US-WEST1",
    "US-WEST2",
    "US-WEST3",
    "US-WEST4",
    "SOUTHAMERICA-EAST1",
    "EUROPE-CENTRAL2",
    "EUROPE-NORTH1",
    "EUROPE-WEST1",
    "EUROPE-WEST2",
    "EUROPE-WEST3",
    "EUROPE-WEST4",
    "EUROPE-WEST6",
    "ASIA-EAST1",
    "ASIA-EAST2",
    "ASIA-NORTHEAST1",
    "ASIA-NORTHEAST2",
    "ASIA-NORTHEAST3",
    "ASIA-SOUTH1",
    "ASIA-SOUTH2",
    "ASIA-SOUTHEAST1",
    "ASIA-SOUTHEAST2",
    "AUSTRALIA-SOUTHEAST1",
    "AUSTRALIA-SOUTHEAST2",
]

storage_classes_list = [
    "STANDARD",
    "NEARLINE",
    "COLDLINE",
    "ARCHIVE",
]
